// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.weierp.domain.manager;

import com.zzl.weierp.domain.manager.Manager;
import com.zzl.weierp.domain.manager.ManagerDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ManagerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ManagerDataOnDemand: @Component;
    
    private Random ManagerDataOnDemand.rnd = new SecureRandom();
    
    private List<Manager> ManagerDataOnDemand.data;
    
    public Manager ManagerDataOnDemand.getNewTransientManager(int index) {
        Manager obj = new Manager();
        setPassword(obj, index);
        setSerial(obj, index);
        setUsername(obj, index);
        return obj;
    }
    
    public void ManagerDataOnDemand.setPassword(Manager obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public void ManagerDataOnDemand.setSerial(Manager obj, int index) {
        String serial = "serial_" + index;
        obj.setSerial(serial);
    }
    
    public void ManagerDataOnDemand.setUsername(Manager obj, int index) {
        String username = "username_" + index;
        obj.setUsername(username);
    }
    
    public Manager ManagerDataOnDemand.getSpecificManager(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Manager obj = data.get(index);
        Long id = obj.getId();
        return Manager.findManager(id);
    }
    
    public Manager ManagerDataOnDemand.getRandomManager() {
        init();
        Manager obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Manager.findManager(id);
    }
    
    public boolean ManagerDataOnDemand.modifyManager(Manager obj) {
        return false;
    }
    
    public void ManagerDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Manager.findManagerEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Manager' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Manager>();
        for (int i = 0; i < 10; i++) {
            Manager obj = getNewTransientManager(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
