// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.weierp.domain.manager;

import com.zzl.weierp.domain.manager.Manager;
import com.zzl.weierp.domain.manager.ManagerDataOnDemand;
import com.zzl.weierp.domain.manager.ManagerIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ManagerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ManagerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ManagerIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ManagerIntegrationTest: @Transactional;
    
    @Autowired
    ManagerDataOnDemand ManagerIntegrationTest.dod;
    
    @Test
    public void ManagerIntegrationTest.testCountManagers() {
        Assert.assertNotNull("Data on demand for 'Manager' failed to initialize correctly", dod.getRandomManager());
        long count = Manager.countManagers();
        Assert.assertTrue("Counter for 'Manager' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ManagerIntegrationTest.testFindManager() {
        Manager obj = dod.getRandomManager();
        Assert.assertNotNull("Data on demand for 'Manager' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Manager' failed to provide an identifier", id);
        obj = Manager.findManager(id);
        Assert.assertNotNull("Find method for 'Manager' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Manager' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ManagerIntegrationTest.testFindAllManagers() {
        Assert.assertNotNull("Data on demand for 'Manager' failed to initialize correctly", dod.getRandomManager());
        long count = Manager.countManagers();
        Assert.assertTrue("Too expensive to perform a find all test for 'Manager', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Manager> result = Manager.findAllManagers();
        Assert.assertNotNull("Find all method for 'Manager' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Manager' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ManagerIntegrationTest.testFindManagerEntries() {
        Assert.assertNotNull("Data on demand for 'Manager' failed to initialize correctly", dod.getRandomManager());
        long count = Manager.countManagers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Manager> result = Manager.findManagerEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Manager' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Manager' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ManagerIntegrationTest.testFlush() {
        Manager obj = dod.getRandomManager();
        Assert.assertNotNull("Data on demand for 'Manager' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Manager' failed to provide an identifier", id);
        obj = Manager.findManager(id);
        Assert.assertNotNull("Find method for 'Manager' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyManager(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Manager' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ManagerIntegrationTest.testMergeUpdate() {
        Manager obj = dod.getRandomManager();
        Assert.assertNotNull("Data on demand for 'Manager' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Manager' failed to provide an identifier", id);
        obj = Manager.findManager(id);
        boolean modified =  dod.modifyManager(obj);
        Integer currentVersion = obj.getVersion();
        Manager merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Manager' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ManagerIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Manager' failed to initialize correctly", dod.getRandomManager());
        Manager obj = dod.getNewTransientManager(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Manager' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Manager' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Manager' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ManagerIntegrationTest.testRemove() {
        Manager obj = dod.getRandomManager();
        Assert.assertNotNull("Data on demand for 'Manager' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Manager' failed to provide an identifier", id);
        obj = Manager.findManager(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Manager' with identifier '" + id + "'", Manager.findManager(id));
    }
    
}
