// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.weierp.domain.manager;

import com.zzl.weierp.domain.manager.ManagerDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ManagerDataOnDemand_Roo_Configurable {
    
    declare @type: ManagerDataOnDemand: @Configurable;
    
}
