// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.weierp.domain;

import com.zzl.weierp.domain.ProductType;

privileged aspect ProductType_Roo_JavaBean {
    
    public String ProductType.getName() {
        return this.name;
    }
    
    public void ProductType.setName(String name) {
        this.name = name;
    }
    
}
