// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.weierp.domain.consumer;

import com.zzl.weierp.domain.consumer.ConsumerDetail;
import com.zzl.weierp.domain.consumer.ConsumerDetailDataOnDemand;
import com.zzl.weierp.domain.consumer.ConsumerDetailIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConsumerDetailIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ConsumerDetailIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ConsumerDetailIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ConsumerDetailIntegrationTest: @Transactional;
    
    @Autowired
    ConsumerDetailDataOnDemand ConsumerDetailIntegrationTest.dod;
    
    @Test
    public void ConsumerDetailIntegrationTest.testCountConsumerDetails() {
        Assert.assertNotNull("Data on demand for 'ConsumerDetail' failed to initialize correctly", dod.getRandomConsumerDetail());
        long count = ConsumerDetail.countConsumerDetails();
        Assert.assertTrue("Counter for 'ConsumerDetail' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ConsumerDetailIntegrationTest.testFindConsumerDetail() {
        ConsumerDetail obj = dod.getRandomConsumerDetail();
        Assert.assertNotNull("Data on demand for 'ConsumerDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConsumerDetail' failed to provide an identifier", id);
        obj = ConsumerDetail.findConsumerDetail(id);
        Assert.assertNotNull("Find method for 'ConsumerDetail' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ConsumerDetail' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ConsumerDetailIntegrationTest.testFindAllConsumerDetails() {
        Assert.assertNotNull("Data on demand for 'ConsumerDetail' failed to initialize correctly", dod.getRandomConsumerDetail());
        long count = ConsumerDetail.countConsumerDetails();
        Assert.assertTrue("Too expensive to perform a find all test for 'ConsumerDetail', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ConsumerDetail> result = ConsumerDetail.findAllConsumerDetails();
        Assert.assertNotNull("Find all method for 'ConsumerDetail' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ConsumerDetail' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ConsumerDetailIntegrationTest.testFindConsumerDetailEntries() {
        Assert.assertNotNull("Data on demand for 'ConsumerDetail' failed to initialize correctly", dod.getRandomConsumerDetail());
        long count = ConsumerDetail.countConsumerDetails();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ConsumerDetail> result = ConsumerDetail.findConsumerDetailEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ConsumerDetail' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ConsumerDetail' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ConsumerDetailIntegrationTest.testFlush() {
        ConsumerDetail obj = dod.getRandomConsumerDetail();
        Assert.assertNotNull("Data on demand for 'ConsumerDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConsumerDetail' failed to provide an identifier", id);
        obj = ConsumerDetail.findConsumerDetail(id);
        Assert.assertNotNull("Find method for 'ConsumerDetail' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyConsumerDetail(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ConsumerDetail' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConsumerDetailIntegrationTest.testMergeUpdate() {
        ConsumerDetail obj = dod.getRandomConsumerDetail();
        Assert.assertNotNull("Data on demand for 'ConsumerDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConsumerDetail' failed to provide an identifier", id);
        obj = ConsumerDetail.findConsumerDetail(id);
        boolean modified =  dod.modifyConsumerDetail(obj);
        Integer currentVersion = obj.getVersion();
        ConsumerDetail merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ConsumerDetail' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConsumerDetailIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ConsumerDetail' failed to initialize correctly", dod.getRandomConsumerDetail());
        ConsumerDetail obj = dod.getNewTransientConsumerDetail(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ConsumerDetail' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ConsumerDetail' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ConsumerDetail' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ConsumerDetailIntegrationTest.testRemove() {
        ConsumerDetail obj = dod.getRandomConsumerDetail();
        Assert.assertNotNull("Data on demand for 'ConsumerDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConsumerDetail' failed to provide an identifier", id);
        obj = ConsumerDetail.findConsumerDetail(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ConsumerDetail' with identifier '" + id + "'", ConsumerDetail.findConsumerDetail(id));
    }
    
}
