// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.weierp.domain.consumer;

import com.zzl.weierp.domain.consumer.ConsumerDetailIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ConsumerDetailIntegrationTest_Roo_Configurable {
    
    declare @type: ConsumerDetailIntegrationTest: @Configurable;
    
}
