// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.weierp.domain.consumer;

import com.zzl.weierp.domain.consumer.ConsumerBank;
import com.zzl.weierp.domain.consumer.ConsumerBankDataOnDemand;
import com.zzl.weierp.domain.consumer.ConsumerBankIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConsumerBankIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ConsumerBankIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ConsumerBankIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ConsumerBankIntegrationTest: @Transactional;
    
    @Autowired
    ConsumerBankDataOnDemand ConsumerBankIntegrationTest.dod;
    
    @Test
    public void ConsumerBankIntegrationTest.testCountConsumerBanks() {
        Assert.assertNotNull("Data on demand for 'ConsumerBank' failed to initialize correctly", dod.getRandomConsumerBank());
        long count = ConsumerBank.countConsumerBanks();
        Assert.assertTrue("Counter for 'ConsumerBank' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ConsumerBankIntegrationTest.testFindConsumerBank() {
        ConsumerBank obj = dod.getRandomConsumerBank();
        Assert.assertNotNull("Data on demand for 'ConsumerBank' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConsumerBank' failed to provide an identifier", id);
        obj = ConsumerBank.findConsumerBank(id);
        Assert.assertNotNull("Find method for 'ConsumerBank' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ConsumerBank' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ConsumerBankIntegrationTest.testFindAllConsumerBanks() {
        Assert.assertNotNull("Data on demand for 'ConsumerBank' failed to initialize correctly", dod.getRandomConsumerBank());
        long count = ConsumerBank.countConsumerBanks();
        Assert.assertTrue("Too expensive to perform a find all test for 'ConsumerBank', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ConsumerBank> result = ConsumerBank.findAllConsumerBanks();
        Assert.assertNotNull("Find all method for 'ConsumerBank' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ConsumerBank' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ConsumerBankIntegrationTest.testFindConsumerBankEntries() {
        Assert.assertNotNull("Data on demand for 'ConsumerBank' failed to initialize correctly", dod.getRandomConsumerBank());
        long count = ConsumerBank.countConsumerBanks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ConsumerBank> result = ConsumerBank.findConsumerBankEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ConsumerBank' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ConsumerBank' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ConsumerBankIntegrationTest.testFlush() {
        ConsumerBank obj = dod.getRandomConsumerBank();
        Assert.assertNotNull("Data on demand for 'ConsumerBank' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConsumerBank' failed to provide an identifier", id);
        obj = ConsumerBank.findConsumerBank(id);
        Assert.assertNotNull("Find method for 'ConsumerBank' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyConsumerBank(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ConsumerBank' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConsumerBankIntegrationTest.testMergeUpdate() {
        ConsumerBank obj = dod.getRandomConsumerBank();
        Assert.assertNotNull("Data on demand for 'ConsumerBank' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConsumerBank' failed to provide an identifier", id);
        obj = ConsumerBank.findConsumerBank(id);
        boolean modified =  dod.modifyConsumerBank(obj);
        Integer currentVersion = obj.getVersion();
        ConsumerBank merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ConsumerBank' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConsumerBankIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ConsumerBank' failed to initialize correctly", dod.getRandomConsumerBank());
        ConsumerBank obj = dod.getNewTransientConsumerBank(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ConsumerBank' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ConsumerBank' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ConsumerBank' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ConsumerBankIntegrationTest.testRemove() {
        ConsumerBank obj = dod.getRandomConsumerBank();
        Assert.assertNotNull("Data on demand for 'ConsumerBank' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConsumerBank' failed to provide an identifier", id);
        obj = ConsumerBank.findConsumerBank(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ConsumerBank' with identifier '" + id + "'", ConsumerBank.findConsumerBank(id));
    }
    
}
