// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.weierp.domain.consumer;

import com.zzl.weierp.domain.consumer.ConsumerBank;
import com.zzl.weierp.domain.consumer.ConsumerBankDataOnDemand;
import com.zzl.weierp.domain.consumer.ConsumerDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ConsumerBankDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ConsumerBankDataOnDemand: @Component;
    
    private Random ConsumerBankDataOnDemand.rnd = new SecureRandom();
    
    private List<ConsumerBank> ConsumerBankDataOnDemand.data;
    
    @Autowired
    ConsumerDataOnDemand ConsumerBankDataOnDemand.consumerDataOnDemand;
    
    public ConsumerBank ConsumerBankDataOnDemand.getNewTransientConsumerBank(int index) {
        ConsumerBank obj = new ConsumerBank();
        setBank(obj, index);
        setBankAccount(obj, index);
        setBankUser(obj, index);
        setPayAccount(obj, index);
        return obj;
    }
    
    public void ConsumerBankDataOnDemand.setBank(ConsumerBank obj, int index) {
        String bank = "bank_" + index;
        obj.setBank(bank);
    }
    
    public void ConsumerBankDataOnDemand.setBankAccount(ConsumerBank obj, int index) {
        String bankAccount = "bankAccount_" + index;
        obj.setBankAccount(bankAccount);
    }
    
    public void ConsumerBankDataOnDemand.setBankUser(ConsumerBank obj, int index) {
        String bankUser = "bankUser_" + index;
        obj.setBankUser(bankUser);
    }
    
    public void ConsumerBankDataOnDemand.setPayAccount(ConsumerBank obj, int index) {
        String payAccount = "payAccount_" + index;
        obj.setPayAccount(payAccount);
    }
    
    public ConsumerBank ConsumerBankDataOnDemand.getSpecificConsumerBank(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ConsumerBank obj = data.get(index);
        Long id = obj.getId();
        return ConsumerBank.findConsumerBank(id);
    }
    
    public ConsumerBank ConsumerBankDataOnDemand.getRandomConsumerBank() {
        init();
        ConsumerBank obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ConsumerBank.findConsumerBank(id);
    }
    
    public boolean ConsumerBankDataOnDemand.modifyConsumerBank(ConsumerBank obj) {
        return false;
    }
    
    public void ConsumerBankDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ConsumerBank.findConsumerBankEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ConsumerBank' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ConsumerBank>();
        for (int i = 0; i < 10; i++) {
            ConsumerBank obj = getNewTransientConsumerBank(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
