// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.weierp.domain;

import com.zzl.weierp.domain.Busi;
import com.zzl.weierp.domain.BusiDataOnDemand;
import com.zzl.weierp.domain.BusiIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BusiIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BusiIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BusiIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BusiIntegrationTest: @Transactional;
    
    @Autowired
    BusiDataOnDemand BusiIntegrationTest.dod;
    
    @Test
    public void BusiIntegrationTest.testCountBusis() {
        Assert.assertNotNull("Data on demand for 'Busi' failed to initialize correctly", dod.getRandomBusi());
        long count = Busi.countBusis();
        Assert.assertTrue("Counter for 'Busi' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BusiIntegrationTest.testFindBusi() {
        Busi obj = dod.getRandomBusi();
        Assert.assertNotNull("Data on demand for 'Busi' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Busi' failed to provide an identifier", id);
        obj = Busi.findBusi(id);
        Assert.assertNotNull("Find method for 'Busi' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Busi' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BusiIntegrationTest.testFindAllBusis() {
        Assert.assertNotNull("Data on demand for 'Busi' failed to initialize correctly", dod.getRandomBusi());
        long count = Busi.countBusis();
        Assert.assertTrue("Too expensive to perform a find all test for 'Busi', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Busi> result = Busi.findAllBusis();
        Assert.assertNotNull("Find all method for 'Busi' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Busi' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BusiIntegrationTest.testFindBusiEntries() {
        Assert.assertNotNull("Data on demand for 'Busi' failed to initialize correctly", dod.getRandomBusi());
        long count = Busi.countBusis();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Busi> result = Busi.findBusiEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Busi' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Busi' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BusiIntegrationTest.testFlush() {
        Busi obj = dod.getRandomBusi();
        Assert.assertNotNull("Data on demand for 'Busi' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Busi' failed to provide an identifier", id);
        obj = Busi.findBusi(id);
        Assert.assertNotNull("Find method for 'Busi' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBusi(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Busi' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BusiIntegrationTest.testMergeUpdate() {
        Busi obj = dod.getRandomBusi();
        Assert.assertNotNull("Data on demand for 'Busi' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Busi' failed to provide an identifier", id);
        obj = Busi.findBusi(id);
        boolean modified =  dod.modifyBusi(obj);
        Integer currentVersion = obj.getVersion();
        Busi merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Busi' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BusiIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Busi' failed to initialize correctly", dod.getRandomBusi());
        Busi obj = dod.getNewTransientBusi(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Busi' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Busi' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Busi' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BusiIntegrationTest.testRemove() {
        Busi obj = dod.getRandomBusi();
        Assert.assertNotNull("Data on demand for 'Busi' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Busi' failed to provide an identifier", id);
        obj = Busi.findBusi(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Busi' with identifier '" + id + "'", Busi.findBusi(id));
    }
    
}
