// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.weierp.domain;

import com.zzl.weierp.domain.BusiDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BusiDataOnDemand_Roo_Configurable {
    
    declare @type: BusiDataOnDemand: @Configurable;
    
}
