// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.weierp.domain;

import com.zzl.weierp.domain.OrderProduct;
import com.zzl.weierp.domain.OrderProductDataOnDemand;
import com.zzl.weierp.domain.OrderProductIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OrderProductIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OrderProductIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OrderProductIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: OrderProductIntegrationTest: @Transactional;
    
    @Autowired
    OrderProductDataOnDemand OrderProductIntegrationTest.dod;
    
    @Test
    public void OrderProductIntegrationTest.testCountOrderProducts() {
        Assert.assertNotNull("Data on demand for 'OrderProduct' failed to initialize correctly", dod.getRandomOrderProduct());
        long count = OrderProduct.countOrderProducts();
        Assert.assertTrue("Counter for 'OrderProduct' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OrderProductIntegrationTest.testFindOrderProduct() {
        OrderProduct obj = dod.getRandomOrderProduct();
        Assert.assertNotNull("Data on demand for 'OrderProduct' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OrderProduct' failed to provide an identifier", id);
        obj = OrderProduct.findOrderProduct(id);
        Assert.assertNotNull("Find method for 'OrderProduct' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'OrderProduct' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OrderProductIntegrationTest.testFindAllOrderProducts() {
        Assert.assertNotNull("Data on demand for 'OrderProduct' failed to initialize correctly", dod.getRandomOrderProduct());
        long count = OrderProduct.countOrderProducts();
        Assert.assertTrue("Too expensive to perform a find all test for 'OrderProduct', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<OrderProduct> result = OrderProduct.findAllOrderProducts();
        Assert.assertNotNull("Find all method for 'OrderProduct' illegally returned null", result);
        Assert.assertTrue("Find all method for 'OrderProduct' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OrderProductIntegrationTest.testFindOrderProductEntries() {
        Assert.assertNotNull("Data on demand for 'OrderProduct' failed to initialize correctly", dod.getRandomOrderProduct());
        long count = OrderProduct.countOrderProducts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<OrderProduct> result = OrderProduct.findOrderProductEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'OrderProduct' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'OrderProduct' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OrderProductIntegrationTest.testFlush() {
        OrderProduct obj = dod.getRandomOrderProduct();
        Assert.assertNotNull("Data on demand for 'OrderProduct' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OrderProduct' failed to provide an identifier", id);
        obj = OrderProduct.findOrderProduct(id);
        Assert.assertNotNull("Find method for 'OrderProduct' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOrderProduct(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'OrderProduct' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrderProductIntegrationTest.testMergeUpdate() {
        OrderProduct obj = dod.getRandomOrderProduct();
        Assert.assertNotNull("Data on demand for 'OrderProduct' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OrderProduct' failed to provide an identifier", id);
        obj = OrderProduct.findOrderProduct(id);
        boolean modified =  dod.modifyOrderProduct(obj);
        Integer currentVersion = obj.getVersion();
        OrderProduct merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'OrderProduct' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrderProductIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'OrderProduct' failed to initialize correctly", dod.getRandomOrderProduct());
        OrderProduct obj = dod.getNewTransientOrderProduct(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'OrderProduct' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'OrderProduct' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'OrderProduct' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OrderProductIntegrationTest.testRemove() {
        OrderProduct obj = dod.getRandomOrderProduct();
        Assert.assertNotNull("Data on demand for 'OrderProduct' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OrderProduct' failed to provide an identifier", id);
        obj = OrderProduct.findOrderProduct(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'OrderProduct' with identifier '" + id + "'", OrderProduct.findOrderProduct(id));
    }
    
}
