// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.weierp.domain;

import com.zzl.weierp.domain.BusiDataOnDemand;
import com.zzl.weierp.domain.ProductOrder;
import com.zzl.weierp.domain.ProductOrderDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProductOrderDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductOrderDataOnDemand: @Component;
    
    private Random ProductOrderDataOnDemand.rnd = new SecureRandom();
    
    private List<ProductOrder> ProductOrderDataOnDemand.data;
    
    @Autowired
    BusiDataOnDemand ProductOrderDataOnDemand.busiDataOnDemand;
    
    public ProductOrder ProductOrderDataOnDemand.getNewTransientProductOrder(int index) {
        ProductOrder obj = new ProductOrder();
        setAddress(obj, index);
        setCreateTime(obj, index);
        setNote(obj, index);
        setSerial(obj, index);
        setStatus(obj, index);
        return obj;
    }
    
    public void ProductOrderDataOnDemand.setAddress(ProductOrder obj, int index) {
        String address = "address_" + index;
        obj.setAddress(address);
    }
    
    public void ProductOrderDataOnDemand.setCreateTime(ProductOrder obj, int index) {
        Date createTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreateTime(createTime);
    }
    
    public void ProductOrderDataOnDemand.setNote(ProductOrder obj, int index) {
        String note = "note_" + index;
        obj.setNote(note);
    }
    
    public void ProductOrderDataOnDemand.setSerial(ProductOrder obj, int index) {
        String serial = "serial_" + index;
        obj.setSerial(serial);
    }
    
    public void ProductOrderDataOnDemand.setStatus(ProductOrder obj, int index) {
        int status = index;
        obj.setStatus(status);
    }
    
    public ProductOrder ProductOrderDataOnDemand.getSpecificProductOrder(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProductOrder obj = data.get(index);
        Long id = obj.getId();
        return ProductOrder.findProductOrder(id);
    }
    
    public ProductOrder ProductOrderDataOnDemand.getRandomProductOrder() {
        init();
        ProductOrder obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ProductOrder.findProductOrder(id);
    }
    
    public boolean ProductOrderDataOnDemand.modifyProductOrder(ProductOrder obj) {
        return false;
    }
    
    public void ProductOrderDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProductOrder.findProductOrderEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProductOrder' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProductOrder>();
        for (int i = 0; i < 10; i++) {
            ProductOrder obj = getNewTransientProductOrder(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
