// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.weierp.domain;

import com.zzl.weierp.domain.ProductType;
import com.zzl.weierp.domain.ProductTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ProductTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductTypeDataOnDemand: @Component;
    
    private Random ProductTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<ProductType> ProductTypeDataOnDemand.data;
    
    public ProductType ProductTypeDataOnDemand.getNewTransientProductType(int index) {
        ProductType obj = new ProductType();
        setName(obj, index);
        return obj;
    }
    
    public void ProductTypeDataOnDemand.setName(ProductType obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public ProductType ProductTypeDataOnDemand.getSpecificProductType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProductType obj = data.get(index);
        Long id = obj.getId();
        return ProductType.findProductType(id);
    }
    
    public ProductType ProductTypeDataOnDemand.getRandomProductType() {
        init();
        ProductType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ProductType.findProductType(id);
    }
    
    public boolean ProductTypeDataOnDemand.modifyProductType(ProductType obj) {
        return false;
    }
    
    public void ProductTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProductType.findProductTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProductType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProductType>();
        for (int i = 0; i < 10; i++) {
            ProductType obj = getNewTransientProductType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
