// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.zzl.weierp.domain;

import com.zzl.weierp.domain.ProductType;
import com.zzl.weierp.domain.ProductTypeDataOnDemand;
import com.zzl.weierp.domain.ProductTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductTypeIntegrationTest: @Transactional;
    
    @Autowired
    ProductTypeDataOnDemand ProductTypeIntegrationTest.dod;
    
    @Test
    public void ProductTypeIntegrationTest.testCountProductTypes() {
        Assert.assertNotNull("Data on demand for 'ProductType' failed to initialize correctly", dod.getRandomProductType());
        long count = ProductType.countProductTypes();
        Assert.assertTrue("Counter for 'ProductType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductTypeIntegrationTest.testFindProductType() {
        ProductType obj = dod.getRandomProductType();
        Assert.assertNotNull("Data on demand for 'ProductType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductType' failed to provide an identifier", id);
        obj = ProductType.findProductType(id);
        Assert.assertNotNull("Find method for 'ProductType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProductType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductTypeIntegrationTest.testFindAllProductTypes() {
        Assert.assertNotNull("Data on demand for 'ProductType' failed to initialize correctly", dod.getRandomProductType());
        long count = ProductType.countProductTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProductType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProductType> result = ProductType.findAllProductTypes();
        Assert.assertNotNull("Find all method for 'ProductType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProductType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductTypeIntegrationTest.testFindProductTypeEntries() {
        Assert.assertNotNull("Data on demand for 'ProductType' failed to initialize correctly", dod.getRandomProductType());
        long count = ProductType.countProductTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProductType> result = ProductType.findProductTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProductType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProductType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductTypeIntegrationTest.testFlush() {
        ProductType obj = dod.getRandomProductType();
        Assert.assertNotNull("Data on demand for 'ProductType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductType' failed to provide an identifier", id);
        obj = ProductType.findProductType(id);
        Assert.assertNotNull("Find method for 'ProductType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProductType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ProductType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductTypeIntegrationTest.testMergeUpdate() {
        ProductType obj = dod.getRandomProductType();
        Assert.assertNotNull("Data on demand for 'ProductType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductType' failed to provide an identifier", id);
        obj = ProductType.findProductType(id);
        boolean modified =  dod.modifyProductType(obj);
        Integer currentVersion = obj.getVersion();
        ProductType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ProductType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProductType' failed to initialize correctly", dod.getRandomProductType());
        ProductType obj = dod.getNewTransientProductType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProductType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProductType' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ProductType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductTypeIntegrationTest.testRemove() {
        ProductType obj = dod.getRandomProductType();
        Assert.assertNotNull("Data on demand for 'ProductType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductType' failed to provide an identifier", id);
        obj = ProductType.findProductType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProductType' with identifier '" + id + "'", ProductType.findProductType(id));
    }
    
}
